# -*- coding: utf-8 -*-
"""Escape Character.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/190CBEBjQ1sQwJ4gA6jfqoFV-H8lIAZXZ
"""

print ('Dia berkata : "Pergilah!"')

print ("Aku menimpali: \"Apakah kau ingin aku 'angkat kaki'?!\" ")

print ("\\(^_^/(\\-_-/)")