# -*- coding: utf-8 -*-
"""Manipulasi string.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pim7xB7G2pZbb_WUzsl2SBUqdGFlcda2

**string**
"""

nama = 'Hafidz'
asal = "Bandar Lampung"

print (nama)

print (asal)

"""**manipulasi**"""

print (nama,asal)

print (nama + asal)

print ("hallo, nama saya", nama)

print ("hallo, nama saya", nama, "asal saya dari", asal)

data_lengkap = nama + asal

print (data_lengkap)

"""**string + non string**"""

asal_kota = "bandar lampung"
Kode_pos = 35144

asal_kota_kode_pos = asal_kota + str(Kode_pos)

print (asal_kota_kode_pos)

asal_kota_x3 = asal_kota * 3

print (asal_kota_x3)