# -*- coding: utf-8 -*-
"""Manipulasi stringipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d_0CP18bFWmXq8gjgbpKlwFwAH1w0U3A
"""

template = "halo saya %s dari %s"
print(template %('hafidz mubarok','usa'))

template = 'halo saya{hafidz} dari {tokyo}'
template_2 = 'halo saya makan {} dan minum {}'

print(template.format(hafidz='hafidz',tokyo='indonesia'))
print(template_2.format('mie ayam','es jeruk'))

nama = 'hafidz mubarok'
asal = 'japan'

print(f'perkenalkan saya {nama} dari {asal}')

alamat = 'bandung, jawabarat, papua'

print(alamat.split())
print(alamat.split(','))
print(alamat.split(', '))

print('@'.join(['kamu','gak','suka']))

print('halo selamat pagi!'.upper())
print('halo selamat siang!'.upper())

print('halo selamat pagi!'.lower())
print('halo selamat siang!'.lower())

print('daun tidak pernah membenci angin'.title())
print('laskar pelangi'.title())

print('indonesia adalah negara kepulauan'.swapcase())
print('Aku Cinta Negriku'.swapcase())

angka = '12345'

print('index angka 3:',angka.find('3'))
print('index angka 45:',angka.find('45'))
print('index angka 35:',angka.find('35'))

ibu_kota = 'jakarta'

print(ibu_kota.replace('a','i'))
print(ibu_kota.replace('a',''))

paragraf = 'baru baru ini telah ditemukan sebuah meteor di suatu suangai'
x = paragraf.count('di')

print(f'kata""di"muncul sebanyak {x} kali')