# -*- coding: utf-8 -*-
"""tipe daata casting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g0lvCXNqLU2GPLs04U6K8NR3tgH8yjHP
"""

nama = 'Budi'
usia = 20
lajang = True

print (type(nama))
print (type(usia))
print (type(lajang))

usia = input ('Masukan usia anda:')

print (type(usia))

panjang = int(input('Masukan panjang:'))
lebar = int(input('Masukan lebar:'))

print ('Luas =', panjang * lebar)

a = 10 / 2
 print(type(a))

 b = 1 / 2
 print (type(b))

kata = 'Jeruk' * 5

print (type(kata))
print (kata)

nama = 'Hafidz'
tahun_lahir = 2006

print (nama + 'lahir di tahun' + str(tahun_lahir))