# -*- coding: utf-8 -*-
"""tugas 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YVHBgAQYT1ekejxilOpz0y4jpf6VkKLd
"""

# NX Fikry:
berita = 'Ramai-ramai developer di seluruh dunia mulai menggunakan \
teks editor masa kini seperti Visual Studio Code, \
atom, sublime text, dan lain sebagainya.'

print('sublime text' in berita)
print('notepad++' in berita)

nama = 'hafidz mubarok'

print(nama[4])
print(nama[8])
print(nama[-1])
print(nama[-3])

judul = 'Pelajaran Fisika Untuk SMA'

print(judul[0:5])
print(judul[:10])
print(judul[10:15])
print(judul[-1:-3])
print(judul[:-3])
print(judul[-5:])

print(len('Japan'))
print(len('thailand'))

nomor_telepon_1 = '0871122334455'
nomor_telepon_2 = '87887766555300'
nomor_telepon_3 = '+6233003300390'

kode_negara = '+62'

print(nomor_telepon_1.startswith(kode_negara))
print(nomor_telepon_2.startswith(kode_negara))
print(nomor_telepon_3.startswith(kode_negara))

email_1 = 'presiden@gmail.com'
email_2 = 'presiden@outlook.com'

print(email_1.endswith('gmail.com'))
print(email_2.endswith('gmail.com'))